Build branch
rloterh/BubbleSort pull request #1
Opened 2020-08-04 16:00 UTC by rloterh

- Created 2 bubble sort methods: Bubble_sort and Bubble_sort by
- All test cases running successfully

2020-08-04 21:09 UTC, euqueme requested changes
> ### Pull Request reviewed by Maria Eugenia Queme P. (TSE)

### Hello @rloterh :lollipop: 

### Thank you for your submission :handshake: you've done an amazing job with your `bubble_sort` and `bubble_sort_by` methods you've also had follow Gitflow correctly and your Readme file is professional :necktie: even including a live demo on repl.it so claps to you for that :clap: :clap: :clap: there's just a minor change to make to your `bubble_sort_by` method I've left a comment in your code bellow for you to address it :point_down: 

### That's it! :raised_hands: 

### Please :pray: do the changes :technologist:  and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

2020-08-04 21:09 UTC, euqueme commented on bubble_sort.rb
> +end
- [ ] bubble_sort_by is failing when given an array of Integers let's fix it 

![image](https://user-images.githubusercontent.com/52209067/89344785-aa91a700-d663-11ea-88a1-b61841e72396.png)

2020-08-05 10:06 UTC, rloterh commented
- The code follows the example code given and works fine
- The second method, 'bubble_sort_by' was not to be tested on integers since the length property was used in the example

2020-08-05 10:11 UTC, rloterh commented
-The second method, 'bubble_sort_by' follows the example given in the code
-The 'bubble_sort_by' method was to be tested against integer arrays since length property was used, as can be seen in the example given

2020-08-05 13:13 UTC, mcrd25 approved these changes
# Changes Approved :heavy_check_mark: 

Hi @rloterh :wave: 

Great job!
You were right about `bubble_sort_by` not being meant for integers, that was our bad! :sweat_smile: 
No need for further review! :+1: 

***If you have any questions, now or in the future, do not hesitate to contact me on social media, email or on slack and I will be glad to chat with you.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

2021-04-01 13:32 UTC, rloterh commented
All criteria implemented

2021-04-01 13:32 UTC, closed without merging